[build]
  builder = "DOCKERFILE"
  dockerfilePath = "docker/Dockerfile"

[build.args]
  RAILS_ENV = "production"
  NODE_ENV = "production"
  BUNDLE_WITHOUT = "development:test"

[deploy]
  startCommand = "bundle exec sidekiq -C config/sidekiq.yml"
  restartPolicyType = "ON_FAILURE"
  restartPolicyMaxRetries = 3
