[build]
  builder = "DOCKERFILE"
  dockerfilePath = "docker/Dockerfile"

[build.args]
  RAILS_ENV = "production"
  NODE_ENV = "production"
  BUNDLE_WITHOUT = "development:test"

[deploy]
  startCommand = "bin/rails server -p $PORT -b 0.0.0.0 -e production"
  healthcheckPath = "/auth/sign_in"
  healthcheckTimeout = 300
  restartPolicyType = "ON_FAILURE"
  restartPolicyMaxRetries = 3
